### PR TITLE
Make GitHubPaginationInterceptor more memory efficient.

### LINKED ISSUE #17: GitHubPaginationInterceptor causes OOM for large responses.
From my Crashlytics reports:

```
Caused by java.lang.OutOfMemoryError
Failed to allocate a 28657200 byte allocation with 6291456 free bytes and 13MB until OOM, max allowed footprint 29843656, growth limit 37748736
  | java.util.Arrays.copyOf (Arrays.java:3260)
  | java.lang.String.format (String.java:2770)
  | com.meisolsson.githubsdk.core.GitHubPaginationInterceptor.intercept (GitHubPaginationInterceptor.java:58)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
  | ...
```

The request in question was for https://api.github.com/repos/opengapps/arm64/releases?page=1 which returns a 8.44 MB (!) response.

I'm not sure what the best way to handle this is though; there is no obvious fix for this AFAICT :-(

### PR DESCRIPTION
**Pull request by maniac103**
Use Okio buffers where possible to make sure not to reallocate the
response multiple time, which can cause OOM for large responses.

Closes #17

### CODE REVIEW

**Comment by maniac103** [comment]
Judging from Android Profiler, it looks like before the response size was allocated thrice (the actually response, the string returned by `body().string()` and the output string), while it's only allocated once now.

File: library/src/main/java/com/meisolsson/githubsdk/core/GitHubPaginationInterceptor.java [hunk 1]
```diff
@@ -34,37 +39,50 @@ public Response intercept(Chain chain) throws IOException {
...
+                Charset charset = contentType != null ? contentType.charset(Util.UTF_8) : Util.UTF_8;
+                BufferedSource source = response.body().source();
+                Buffer newResponse = new Buffer();
+
+                try {
+                    source.request(Long.MAX_VALUE);
+
+                    if (isArray) {
+                        newResponse.writeString("{\"items\":", charset);
+                        newResponse.write(source.buffer(), source.buffer().size());
```
Comment (Meisolsson) [inline library/src/main/java/com/meisolsson/githubsdk/core/GitHubPaginationInterceptor.java:72]: Why not use `Buffer.writeAll(Source source)`guessing that would allow us to remove `source.request(...)`

Comment (Meisolsson) [reply library/src/main/java/com/meisolsson/githubsdk/core/GitHubPaginationInterceptor.java:72]: Forget that, saw why that's used further down.
